name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
        strategy:
          fail-fast: false
          matrix:
            config:
              - name: "Pico"
                board_name: pico
              - name: "Pico 2"
                board_name: pico2

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              id: build
              uses: samyarsadat/Pico-Build-Action@v1
              with:
                  source_dir: "."
                  board_name: ${{matrix.config.board_name}}

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: traintastic-cs-${{matrix.config.board_name}}
                  path: ${{steps.build.outputs.output_dir}}
