jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              id: build
              uses: samyarsadat/Pico-Build-Action@v1
              with:
                  source_dir: ""
                  
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: workspace_artifacts
                  path: ${{steps.build.outputs.output_dir}}
